server:
  port: 7000

spring:
  redis:
    host: 192.168.157.131
    port: 6379
    password:
    timeout: 30000
    database: 2
    jedis:
      pool:
        max-wait: 24000
feign:
  httpclient:
    connection-timeout: 30000
    time-to-live: 5000
#    connection-timer-repeat: 30000
#    time-to-live-unit: minutes
#    disable-ssl-validation: true
  compression:
    response:
      enabled: true
    request:
      enabled: true
  client:
    config:
      default:
        read-timeout: 10000