server:
  port: 8001

spring:
  redis:
    host: 192.168.157.131
    database: 1
    password:
    jedis:
      pool:
        max-idle: 5
        max-active: 10
        max-wait: 30000
        min-idle: 0
  cache:
    redis:
      use-key-prefix: true
      key-prefix: auth_
      time-to-live: 180000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fvs?serverTimezone=UTC
    username: root
    password: lhfadmin

ribbon:
  eager-load:
    enabled: true
    clients: sys-user-service
feign:
  client:
    default-to-properties: true
    default-config: default
    config:
      default:
        connect-timeout: 6000
        read-timeout: 6000
#  hystrix:
#    enabled: true
  httpclient:
    connection-timeout: 6000
    time-to-live: 6000
    connection-timer-repeat: 6000

