server:
  port: 8001

spring:
  redis:
    host: 192.168.157.131
    database: 1
    password:
    jedis:
      pool:
        max-idle: 5
        max-active: 10
        max-wait: 30000
        min-idle: 0
  cache:
    redis:
      use-key-prefix: true
      key-prefix: auth_
      time-to-live: 180000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fvs?serverTimezone=UTC
    username: root
    password: lhfadmin


