server:
#  port: 8002
  port: 80
  forward-headers-strategy: native
spring:
  security:
    oauth2:
      client:
        provider:
          uaa:
            authorization-uri: http://192.168.157.131/oauth/authorize
            token-uri: http://192.168.157.131/oauth/token
            user-info-uri: http://192.168.157.131/userinfo
            jwk-set-uri: http://192.168.157.131/token_keys
        registration:
          uaa:
#            provider: uaa
            client-id: e5170418-8560-460b-9296-d7bd95a06a5e
            client-secret: 123
            authorization-grant-type: authorization_code
#            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri: http://localhost:8080/security
            redirect-uri: http://localhost/login/oauth2/code/uaa
            scope: all
