server:
  port: 1103

zuul:
#  add-host-header: true
  sensitive-headers:  Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  host:
    connect-timeout-millis: 8000
    time-to-live: 8000
    connection-request-timeout-millis: 8000
    max-total-connections: 100
    socket-timeout-millis: 8000
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
  ribbon:
    eager-load:
      enabled: true
  prefix: /api
  routes:
    oauth-authorize:
      path: /auth/**
      service-id: sys-fvs-auth
    sys-user:
      path: /user/**
      service-id: sys-user-api


