spring:
  profiles:
    active: dev



mybatis-plus:
  type-aliases-package: com.lhf.sysfvscommon.*.**
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
feign:
  httpclient:
    connection-timeout: 3000
    time-to-live: 3000
    connection-timer-repeat: 3000
  compression:
    response:
      enabled: true
      useGzipDecoder: true
    request:
      enabled: true
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  client:
    default-to-properties: true
    default-config: default
    config:
      default:
        read-timeout: 40000
        connect-timeout: 40000

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 300000
#      circuitBreaker:
#        sleepWindowInMilliseconds: 300000
#        forceClosed: true


